'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

x1,x2=1,2
MAX_VALUE = 4000000
ret=2
while True:
    x1=x1+x2
    x2=x1+x2
    if x1>MAX_VALUE or x2>MAX_VALUE:
        break
    if x1%2==0:
        ret+=x1
    if x2%2==0:
        ret+=x2
print(ret)

